from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    arguments = [
        DeclareLaunchArgument('use_sim_time', default_value='true'),
        DeclareLaunchArgument('scan_topic', default_value='/scan'),
        DeclareLaunchArgument('odom_topic', default_value='/odom'),
        DeclareLaunchArgument('cmd_vel_topic', default_value='/cmd_vel_obstacle'),
        DeclareLaunchArgument('front_half_angle_deg', default_value='25.0'),
        DeclareLaunchArgument('side_sector_min_deg', default_value='30.0'),
        DeclareLaunchArgument('side_sector_max_deg', default_value='120.0'),
        DeclareLaunchArgument('avoid_distance', default_value='0.95'),
        DeclareLaunchArgument('clear_distance', default_value='1.05'),
        DeclareLaunchArgument('emergency_distance', default_value='0.50'),
        DeclareLaunchArgument('side_clearance_min', default_value='0.35'),
        DeclareLaunchArgument('stop_time_sec', default_value='0.10'),
        DeclareLaunchArgument('turn_time_sec', default_value='1.80'),
        DeclareLaunchArgument('forward_time_sec', default_value='8.00'),
        DeclareLaunchArgument('forward_min_distance', default_value='0.32'),
        DeclareLaunchArgument('min_turn_away_time_sec', default_value='0.75'),
        DeclareLaunchArgument('turn_back_time_sec', default_value='4.00'),
        DeclareLaunchArgument('turn_back_yaw_tolerance_deg', default_value='5.0'),
        DeclareLaunchArgument('turn_speed', default_value='0.25'),
        DeclareLaunchArgument('forward_speed', default_value='0.100'),
        DeclareLaunchArgument('rejoin_speed', default_value='0.035'),
        DeclareLaunchArgument('search_rejoin_speed', default_value='0.025'),
        DeclareLaunchArgument('search_rejoin_turn_speed', default_value='0.08'),
        DeclareLaunchArgument('rejoin_kp', default_value='0.0025'),
        DeclareLaunchArgument('rejoin_block_distance', default_value='0.50'),
        DeclareLaunchArgument('rejoin_release_distance', default_value='0.58'),
        DeclareLaunchArgument('rejoin_block_confirm_frames', default_value='3'),
        DeclareLaunchArgument('rejoin_block_turn_sec', default_value='0.80'),
        DeclareLaunchArgument('rejoin_max_ang', default_value='0.18'),
        DeclareLaunchArgument('line_rejoin_error_thresh', default_value='35.0'),
        DeclareLaunchArgument('line_rejoin_confirm_frames', default_value='8'),
        DeclareLaunchArgument('max_rejoin_time_sec', default_value='6.0'),
        DeclareLaunchArgument('publish_rate_hz', default_value='20.0'),
    ]

    avoid_node = Node(
        package='tb3_safety',
        executable='obstacle_avoid',
        name='obstacle_avoid',
        output='screen',
        parameters=[{
            'use_sim_time': LaunchConfiguration('use_sim_time'),
            'scan_topic': LaunchConfiguration('scan_topic'),
            'odom_topic': LaunchConfiguration('odom_topic'),
            'cmd_vel_topic': LaunchConfiguration('cmd_vel_topic'),
            'front_half_angle_deg': LaunchConfiguration('front_half_angle_deg'),
            'side_sector_min_deg': LaunchConfiguration('side_sector_min_deg'),
            'side_sector_max_deg': LaunchConfiguration('side_sector_max_deg'),
            'avoid_distance': LaunchConfiguration('avoid_distance'),
            'clear_distance': LaunchConfiguration('clear_distance'),
            'emergency_distance': LaunchConfiguration('emergency_distance'),
            'side_clearance_min': LaunchConfiguration('side_clearance_min'),
            'stop_time_sec': LaunchConfiguration('stop_time_sec'),
            'turn_time_sec': LaunchConfiguration('turn_time_sec'),
            'forward_time_sec': LaunchConfiguration('forward_time_sec'),
            'forward_min_distance': LaunchConfiguration('forward_min_distance'),
            'min_turn_away_time_sec': LaunchConfiguration('min_turn_away_time_sec'),
            'turn_back_time_sec': LaunchConfiguration('turn_back_time_sec'),
            'turn_back_yaw_tolerance_deg': LaunchConfiguration('turn_back_yaw_tolerance_deg'),
            'turn_speed': LaunchConfiguration('turn_speed'),
            'forward_speed': LaunchConfiguration('forward_speed'),
            'rejoin_speed': LaunchConfiguration('rejoin_speed'),
            'search_rejoin_speed': LaunchConfiguration('search_rejoin_speed'),
            'search_rejoin_turn_speed': LaunchConfiguration('search_rejoin_turn_speed'),
            'rejoin_kp': LaunchConfiguration('rejoin_kp'),
            'rejoin_block_distance': LaunchConfiguration('rejoin_block_distance'),
            'rejoin_release_distance': LaunchConfiguration('rejoin_release_distance'),
            'rejoin_block_confirm_frames': LaunchConfiguration('rejoin_block_confirm_frames'),
            'rejoin_block_turn_sec': LaunchConfiguration('rejoin_block_turn_sec'),
            'rejoin_max_ang': LaunchConfiguration('rejoin_max_ang'),
            'line_rejoin_error_thresh': LaunchConfiguration('line_rejoin_error_thresh'),
            'line_rejoin_confirm_frames': LaunchConfiguration('line_rejoin_confirm_frames'),
            'max_rejoin_time_sec': LaunchConfiguration('max_rejoin_time_sec'),
            'publish_rate_hz': LaunchConfiguration('publish_rate_hz'),
        }],
    )

    return LaunchDescription(arguments + [avoid_node])
